id: 07986d3b-e3d8-4d63-9966-6d8458051975
type: application
interactions:
- targetId: cf975ce2-a5bd-4d78-8e16-8298660e4d9e
  type: service
  level: component
- targetId: e717a75c-614a-4940-9cd7-ad6ae207c601
  type: domain
  level: component
annotations:
- namespace: c4modeler
  name: position
  value:
    80afd6e9-c844-4620-8ccc-4c11e6cfbbc1:
      x: 140
      y: 124.5
name: NewApplication
description: Description for NewApplication
baseApiUrl: ca/baseapi
